# Generated by Django 4.2.20 on 2025-04-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
    ]
