# Generated by Django 4.2.20 on 2025-04-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likes',
            new_name='liked_by',
        ),
    ]
