# Generated by Django 4.2.20 on 2025-04-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_remove_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Date_of_birth',
            field=models.DateField(blank=True, default='yyyy-mm-d', max_length=10, null=True),
        ),
    ]
