# Generated by Django 4.2.20 on 2025-04-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend_request',
            new_name='FriendRequest',
        ),
        migrations.AlterField(
            model_name='createpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Date_of_birth',
            field=models.DateField(blank=True, default='2000-08-01', max_length=10, null=True),
        ),
    ]
