# Generated by Django 4.2.20 on 2025-04-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0004_rename_friend_request_friendrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
