# Generated by Django 4.2.20 on 2025-04-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0005_alter_customuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
    ]
