# Generated by Django 4.2.20 on 2025-04-28 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0006_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
