# Generated by Django 4.2.20 on 2025-04-29 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 4, 31, 7, 595187, tzinfo=datetime.timezone.utc)),
        ),
    ]
