# Generated by Django 4.2.20 on 2025-04-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0008_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='fb.create_post'),
        ),
        migrations.AlterField(
            model_name='create_post',
            name='user',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='fb.userprofile'),
        ),
    ]
