# Generated by Django 4.2.20 on 2025-04-29 04:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0009_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 4, 33, 54, 283069, tzinfo=datetime.timezone.utc)),
        ),
    ]
