# Generated by Django 4.2.20 on 2025-04-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0012_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
