# Generated by Django 4.2.20 on 2025-04-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0013_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
