# Generated by Django 4.2.20 on 2025-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0014_alter_create_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_post',
            new_name='CreatePost',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
