# Generated by Django 4.2.20 on 2025-04-16 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0016_alter_createpost_user_alter_friend_request_to_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='createpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb.userprofile'),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='userfrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfrom', to=settings.AUTH_USER_MODEL),
        ),
    ]
