# Generated by Django 4.2.21 on 2025-05-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0016_rename_friend_request_friendrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Date_of_birth',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('NONE', 'Prefer not to say')], default='NONE', max_length=20),
        ),
    ]
