# Generated by Django 4.2.21 on 2025-05-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0017_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
