# Generated by Django 4.2.20 on 2025-04-16 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0017_remove_userprofile_user_alter_createpost_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Surname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
