# Generated by Django 4.2.21 on 2025-05-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_alter_friendrequest_from_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
    ]
