# Generated by Django 4.2.21 on 2025-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0006_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
