# Generated by Django 4.2.21 on 2025-05-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0007_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
