# Generated by Django 4.2.21 on 2025-06-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0011_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
