# Generated by Django 4.2.21 on 2025-06-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0012_remove_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
