# Generated by Django 4.2.21 on 2025-06-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0018_comment_parent_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
