# Generated by Django 4.2.21 on 2025-06-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0021_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
