# Generated by Django 4.2.21 on 2025-06-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0023_customuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_permium',
            field=models.BooleanField(default=False),
        ),
    ]
