# Generated by Django 4.2.21 on 2025-06-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0025_alter_customuser_is_permium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_permium',
            field=models.BooleanField(default=False),
        ),
    ]
