# Generated by Django 4.2.21 on 2025-07-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0026_alter_customuser_is_permium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_permium',
            new_name='is_premium',
        ),
    ]
