# Generated by Django 4.2.21 on 2025-07-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0027_rename_is_permium_customuser_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
