# Generated by Django 4.2.21 on 2025-07-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0028_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
